---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the helm values file over
      copy:
        src: ingress-values.yml
        dest: $HOME/

    - name: Use helm to deploy the ingress-controller
      shell: helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx -f ingress-values.yml
      args:
        chdir: $HOME
    - name: Pause for 30 seconds becasue ingress sometimes needs some time.
      ansible.builtin.pause:
        seconds: 30
